// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZLAEMXJDL0uhcVqNeE0n3d-ffozDOexM',
    appId: '1:88721190456:web:d16b4e2af9448e5e6e00cd',
    messagingSenderId: '88721190456',
    projectId: 'activityhub-1f488',
    authDomain: 'activityhub-1f488.firebaseapp.com',
    storageBucket: 'activityhub-1f488.firebasestorage.app',
    measurementId: 'G-LQ96MHMYJ1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVkmZfDG4OCeGPXXdKeUnAPfix7zEz3_Y',
    appId: '1:88721190456:ios:5b9e73acbfc723326e00cd',
    messagingSenderId: '88721190456',
    projectId: 'activityhub-1f488',
    storageBucket: 'activityhub-1f488.firebasestorage.app',
    iosBundleId: 'com.example.activityhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVkmZfDG4OCeGPXXdKeUnAPfix7zEz3_Y',
    appId: '1:88721190456:ios:5b9e73acbfc723326e00cd',
    messagingSenderId: '88721190456',
    projectId: 'activityhub-1f488',
    storageBucket: 'activityhub-1f488.firebasestorage.app',
    iosBundleId: 'com.example.activityhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZLAEMXJDL0uhcVqNeE0n3d-ffozDOexM',
    appId: '1:88721190456:web:9d1db5b1a85f9b076e00cd',
    messagingSenderId: '88721190456',
    projectId: 'activityhub-1f488',
    authDomain: 'activityhub-1f488.firebaseapp.com',
    storageBucket: 'activityhub-1f488.firebasestorage.app',
    measurementId: 'G-16MQZ13N6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvaeyMNBsiY5fnnILZZbseAbY5ujadbPA',
    appId: '1:88721190456:android:dacfdd6966166d1d6e00cd',
    messagingSenderId: '88721190456',
    projectId: 'activityhub-1f488',
    storageBucket: 'activityhub-1f488.firebasestorage.app',
  );

}